### ISSUE TITLE
Args slice bug

### ISSUE THREAD

**Issue by ColCh** [bahmutov/start-server-and-test#153]
## Is this a bug report or a feature request?

bug report

- version 1.7.12
- platform mac os mojave
- expected behavior no error
- actual behavior error

## info

patched package a bit to show debug info

![image](https://user-images.githubusercontent.com/599439/54667759-3b62f380-4afe-11e9-9998-5380c173d31f.png)

and ran this

```
npx cross-env FOO=bar start-server-and-test webpack-dev-server http://localhost:9876 karma:test --log-level=DEBUG
```

got this error

```
npx cross-env FOO=bar start-server-and-test webpack-dev-server http://localhost:9876 karma:test --log-level=DEBUG
start-server-and-test: args.length -> 4
----------- start dump args  --------------
[ 'webpack-dev-server',
  'http://localhost:9876',
  'karma:test',
  '--log-level=DEBUG' ]
----------- done dump args  --------------
/Users/colch/Documents/Workspace/HelloWorldGreeterEnterprise/node_modules/lazy-ass/index.js:117
      throw err;
      ^

Error: expect: <start script name> <url> <test script name>
    at lazyAssLogic (/Users/colch/Documents/Workspace/HelloWorldGreeterEnterprise/node_modules/lazy-ass/index.js:110:14)
    at lazyAss (/Users/colch/Documents/Workspace/HelloWorldGreeterEnterprise/node_modules/lazy-ass/index.js:115:28)
    at Object.<anonymous> (/Users/colch/Documents/Workspace/HelloWorldGreeterEnterprise/node_modules/start-server-and-test/bin/start.js:36:3)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

package now allows to specify things and forces me to wrap everything :(

BTW do you need help with fix?

**Comment by bahmutov** [comment]
This utility does not allow passing arguments to the server or to the test script yet, see #88

**Comment by ColCh** [comment]
Ok thank you. Closing in flavor of #88
