### ISSUE TITLE
Missing Dependency

### ISSUE THREAD

**Issue by JeffWeim** [bahmutov/start-server-and-test#229]
## Bug Report

- version
`1.10.7`
- platform
N/A
- expected behavior
Package installs properly and runs
- actual behavior
Getting this error 
```
Error: Cannot find module 'strip-final-newline'
Require stack:
- /[...]/node_modules/start-server-and-test/node_modules/execa/index.js
- /[...]/node_modules/start-server-and-test/src/index.js
- /[...]/node_modules/start-server-and-test/src/bin/start.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:973:15)
    at Function.Module._load (internal/modules/cjs/loader.js:855:27)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/[...]/node_modules/start-server-and-test/node_modules/execa/index.js:5:27)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/[...]/node_modules/start-server-and-test/node_modules/execa/index.js',
    '/[...]/node_modules/start-server-and-test/src/index.js',
    '/[...]/node_modules/start-server-and-test/src/bin/start.js'
  ]
}
```

**Comment by bahmutov** [comment]
hmm, let me check - it seems to be defined as a production dependency of `execa`
```
$ npm ls strip-final-newline
start-server-and-test@0.0.0-development /Users/gleb/git/start-server-and-test
└─┬ execa@2.1.0
  └── strip-final-newline@2.0.0
```
I can see it declared
```
$ cat node_modules/execa/package.json
...
"strip-final-newline": "^2.0.0"
```

Can you do `npm ls strip-final-newline`?

**Comment by bahmutov** [comment]
also note: all top level dependencies are checked using a command
```
$ npm run deps

> start-server-and-test@0.0.0-development deps /Users/gleb/git/start-server-and-test
> deps-ok && dependency-check --no-dev .

Success! All dependencies used in the code are listed in package.json
```
