### ISSUE TITLE
Cannot find module 'lodash/fp'

### ISSUE THREAD

**Issue by bmitchinson** [bahmutov/start-server-and-test#269]
```
> peach@0.1.0 travis-start-and-test /home/travis/build/graze-analytics/peach
> start-server-and-test start http://localhost:3000 cy:run
internal/modules/cjs/loader.js:965
  throw err;
  ^
Error: Cannot find module 'lodash/fp'
Require stack:
- /home/travis/build/graze-analytics/peach/node_modules/wait-on/lib/wait-on.js
- /home/travis/build/graze-analytics/peach/node_modules/start-server-and-test/src/index.js
- /home/travis/build/graze-analytics/peach/node_modules/start-server-and-test/src/bin/start.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:962:15)
    at Function.Module._load (internal/modules/cjs/loader.js:838:27)
    at Module.require (internal/modules/cjs/loader.js:1022:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/travis/build/graze-analytics/peach/node_modules/wait-on/lib/wait-on.js:8:72)
    at Module._compile (internal/modules/cjs/loader.js:1118:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Function.Module._load (internal/modules/cjs/loader.js:875:14)
    at Module.require (internal/modules/cjs/loader.js:1022:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/travis/build/graze-analytics/peach/node_modules/wait-on/lib/wait-on.js',
    '/home/travis/build/graze-analytics/peach/node_modules/start-server-and-test/src/index.js',
    '/home/travis/build/graze-analytics/peach/node_modules/start-server-and-test/src/bin/start.js'
  ]
}
```
## Is this a bug report or a feature request?
Bug Report

- version: node: 13.14 + start-server-and-test: 1.11
- platform: MacOS + Travis (linux)
- expected behavior: the command executes
- actual behavior: the command fails

Feel like I'm making a silly mistake here. Any ideas?

**Comment by j-chao** [comment]
I get the same error.

**Comment by brunachamon-hotmart** [comment]
same here =(

**Comment by mj12albert** [comment]
got this error while updating cypress from `4.8.0` to `4.10.0`... fixed by updating my lodash dependency to `"lodash": "^4.17.19"`
start-server-and-test is `1.11.0` (has been for a while)
works on macos + circleci (node 12.16.2)

**Comment by bmitchinson** [comment]
This dependency bot upgrade would fix it: 

https://github.com/bahmutov/start-server-and-test/pull/257

It updates wait-on to v5, which updates lodash to 4.17.19, which fixes this dep error
