### ISSUE TITLE
Throws an error on GitlabCI

### ISSUE THREAD

**Issue by IgorBabkin** [bahmutov/start-server-and-test#281]
It works properly on gitlab ci but at the end it throws strange error

```
events.js:292
      throw er; // Unhandled 'error' event
      ^
Error: spawn ps ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn ps',
  path: 'ps',
  spawnargs: [ '-A', '-o', 'ppid,pid,stat,comm' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

package.json
```
    "test:unit": "jest src/*",
    "server": "cross-env ENTRY_POINT=main webpack --config webpack.dev.js && http-server dist -p 3330",
    "test:e2e": "start-test server http://localhost:3330 test:unit",
[gitlab-ci.output.txt](https://github.com/bahmutov/start-server-and-test/files/5161701/gitlab-ci.output.txt)

```

**Comment by alexander2001i** [comment]
It does the same on Github Actions. Output:

```
| events.js:174
|       throw er; // Unhandled 'error' event
|       ^
| 
| Error: spawn ps ENOENT
|     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
|     at onErrorNT (internal/child_process.js:415:16)
|     at process._tickCallback (internal/process/next_tick.js:63:19)
| Emitted 'error' event at:
|     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
|     at onErrorNT (internal/child_process.js:415:16)
|     at process._tickCallback (internal/process/next_tick.js:63:19)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by samlucax** [comment]
Same on Azure #253 and CircleCI #250 

@bahmutov any idea on what can it be?

**Comment by IgorBabkin** [comment]
I've switched to [wait-on](https://www.npmjs.com/package/wait-on) from `start-server-and-test`. It works for my case

**Comment by petermanders89** [comment]
It seems that the gitlab-runner is missing a dependency. I solved it by doing the following: https://github.com/bahmutov/start-server-and-test/issues/132#issuecomment-448581335

**Comment by MikeMcC399** [comment]
The [README > Install](https://github.com/bahmutov/start-server-and-test#install) section has been updated to include the following text:

If you are running on Linux, ensure that `ps` is available. Minimal Docker images, such as `node:slim`, may not include this by default. On Debian, `ps` is included in the `procps` package, which may need to be installed additionally. Detailed requirements are listed in the dependency documentation [tree-kill > Methods](https://github.com/pkrumins/node-tree-kill#methods).
