### ISSUE TITLE
Regression wait-on

### ISSUE THREAD

**Issue by akoidan** [bahmutov/start-server-and-test#283]
This worked perfectly on version start-server-and-test@1.10.8. After updating to version  start-server-and-test@1.11.4 this package stopped working.
```
Platform MacOS@10.15.3
Node v14.12.0
```
Reproduce

```
yarn init
yarn add servor@4.0.2
yarn add start-server-and-test@1.11.4
mkdir dist; echo "<div>Hello</div>" > dist/index.html
yarn run start-server-and-test 'servor dist index.html 8080' http//localhost:8080 'echo done'
```

**expected behavior**:
`done` on stdout and process' exit.

**actual behavior**:
```
^[^[Error: Timed out waiting for: http://localhost:8080
    at MergeMapSubscriber.project (/Users/deathangel908/WebstormProjects/vue-webpack-ts-ncu/node_modules/wait-on/lib/wait-on.js:130:25)
    at MergeMapSubscriber._tryNext (/Users/deathangel908/WebstormProjects/vue-webpack-ts-ncu/node_modules/rxjs/internal/operators/mergeMap.js:67:27)
    at MergeMapSubscriber._next (/Users/deathangel908/WebstormProjects/vue-webpack-ts-ncu/node_modules/rxjs/internal/operators/mergeMap.js:57:18)
    at MergeMapSubscriber.Subscriber.next (/Users/deathangel908/WebstormProjects/vue-webpack-ts-ncu/node_modules/rxjs/internal/Subscriber.js:66:18)
    at AsyncAction.dispatch [as work] (/Users/deathangel908/WebstormProjects/vue-webpack-ts-ncu/node_modules/rxjs/internal/observable/timer.js:31:16)
    at AsyncAction._execute (/Users/deathangel908/WebstormProjects/vue-webpack-ts-ncu/node_modules/rxjs/internal/scheduler/AsyncAction.js:71:18)
    at AsyncAction.execute (/Users/deathangel908/WebstormProjects/vue-webpack-ts-ncu/node_modules/rxjs/internal/scheduler/AsyncAction.js:59:26)
    at AsyncScheduler.flush (/Users/deathangel908/WebstormProjects/vue-webpack-ts-ncu/node_modules/rxjs/internal/scheduler/AsyncScheduler.js:52:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

The server meanwhile was up and running

**Comment by herrmannplatz** [comment]
Can confirm what @carhartl said. Works as expected on Node v16, but times out on v17

**Comment by rtrembecky** [comment]
I can double-confirm here, having issues with node 17, where 16 works. Have you guys figured out some workaround or something?

**Comment by aarowman** [comment]
We are having an issue too, using version `1.14` here, saw it with Node v16.

After `start-server-and-test` times out, the process does not exit, just hangs there indefinitely.
