### ISSUE TITLE
Task not run when used with Vite server

### ISSUE THREAD

**Issue by oliverturner** [bahmutov/start-server-and-test#313]
## Intro

When used with Vite `start-server-and-test` fails to run the specified subtask

This is a continuation of the prematurely closed bahmutov/start-server-and-test/issues/312 but additionally provides a minimal repro:
https://github.com/oliverturner/start-server-vite-minimal-repro

### Version: 
- "start-server-and-test": "1.13.1",
- "vite": "2.4.4"

### Platform: 
System:
- OS: macOS 11.5.1
- CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
- Memory: 203.41 MB / 16.00 GB
- Shell: 3.3.1 - /usr/local/bin/fish

Binaries:
- Node: 12.22.3 - ~/.volta/tools/image/node/12.22.3/bin/node
- npm: 7.20.2 - ~/.volta/tools/image/npm/7.20.2/bin/npm

### Expected behavior
The specified task is run after Vite has spun up

### Actual behavior
Vite starts but the task is not run

CLI output:
```
> start-server-vite-minimal-repro@0.0.0 test
> start-test dev 3000 subtask

1: starting server using command "npm run dev"
and when url "[ 'http://localhost:3000' ]" is responding with HTTP status code 200
running tests using command "npm run subtask"


> start-server-vite-minimal-repro@0.0.0 dev
> vite --clearScreen false


  vite v2.4.4 dev server running at:

  > Local: http://localhost:3000/
  > Network: use `--host` to expose

  ready in 149ms.
```
Subsequently...
```
Error: Timed out waiting for: http://localhost:3000
    at /Users/oliver.turner/Dev/xpmt/vite/start-server-vite-minimal-repro/node_modules/wait-on/lib/wait-on.js:132:31
    at doInnerSub (/Users/oliver.turner/Dev/xpmt/vite/start-server-vite-minimal-repro/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:21:26)
    at outerNext (/Users/oliver.turner/Dev/xpmt/vite/start-server-vite-minimal-repro/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:16:70)
    at OperatorSubscriber._this._next (/Users/oliver.turner/Dev/xpmt/vite/start-server-vite-minimal-repro/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:28:21)
    at OperatorSubscriber.Subscriber.next (/Users/oliver.turner/Dev/xpmt/vite/start-server-vite-minimal-repro/node_modules/rxjs/dist/cjs/internal/Subscriber.js:72:18)
    at AsyncAction.work (/Users/oliver.turner/Dev/xpmt/vite/start-server-vite-minimal-repro/node_modules/rxjs/dist/cjs/internal/observable/timer.js:28:28)
    at AsyncAction._execute (/Users/oliver.turner/Dev/xpmt/vite/start-server-vite-minimal-repro/node_modules/rxjs/dist/cjs/internal/scheduler/AsyncAction.js:76:18)
    at AsyncAction.execute (/Users/oliver.turner/Dev/xpmt/vite/start-server-vite-minimal-repro/node_modules/rxjs/dist/cjs/internal/scheduler/AsyncAction.js:64:26)
    at AsyncScheduler.flush (/Users/oliver.turner/Dev/xpmt/vite/start-server-vite-minimal-repro/node_modules/rxjs/dist/cjs/internal/scheduler/AsyncScheduler.js:39:33)
```

**Comment by bahmutov** [comment]
Have you read https://github.com/bahmutov/start-server-and-test#note-for-webpack-dev-server-users ?

**Comment by oliverturner** [comment]
Thank you for the pointer. Having read it, here's the output of running Vite and `wait-on` in parallel:

Terminal tab 1:
```
start-server-vite-minimal-repro on  main via  v12.22.3
➜ npm run dev

> start-server-vite-minimal-repro@0.0.0 dev
> vite --clearScreen false


  vite v2.4.4 dev server running at:

  > Local: http://localhost:3000/
  > Network: use `--host` to expose

  ready in 334ms.
```

Terminal tab 2:
```
start-server-vite-minimal-repro on  main via  v12.22.3
➜ npx wait-on -lv http://localhost:3000/index.html
waiting for 1 resources: http://localhost:3000/index.html
making HTTP(S) head request to  url:http://localhost:3000/index.html ...
  HTTP(S) result for http://localhost:3000/index.html: {
  status: 200,
  statusText: 'OK',
  headers: {
    'access-control-allow-origin': '*',
    'content-type': 'text/html',
    'cache-control': 'no-cache',
    etag: 'W/"197-lq2+FOV5/NFodCUBMeCoaeYaQtc"',
    date: 'Tue, 03 Aug 2021 08:17:47 GMT',
    connection: 'close'
  },
  data: ''
}
wait-on(2881) complete
```

It appears that the issue is unrelated to the http verb used (`http-get:` also succeeds)
