### ISSUE TITLE
Timeout waiting for site

### ISSUE THREAD

**Issue by dereklin** [bahmutov/start-server-and-test#323]
Thank you for taking time to open a new issue. Please answer a few questions to help us fix it faster. You can delete text that is irrelevant to the issue.

## Is this a bug report or a feature request?
Could you be bug, but not sure

If this is a bug report, please provide as much info as possible

- version: 1.14.0
- platform: linux
- expected behavior: wait for Angular app compilation to finish before checking target site
- actual behavior: times out looking for the target site when Angular compilation is not yet done

I am using start-server-and-test in a fairly large Angular 12 app.  Things work nicely on my local environment with Mac os.  But when the ci pipeline runs in linux, I get a timeout error:

```
...
Compiling ng2-pdfjs-viewer : module as esm5
Compiling cdk-table-exporter : es2015 as esm2015
Error: Timed out waiting for: https://localhost:3000/app/login
    at /builds/vN1UpTSL/18/bdc/neo2.0/node_modules/wait-on/lib/wait-on.js:132:31
    at doInnerSub (/builds/vN1UpTSL/18/bdc/neo2.0/node_modules/wait-on/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:22:31)
    at outerNext (/builds/vN1UpTSL/18/bdc/neo2.0/node_modules/wait-on/node_modules/rxjs/dist/cjs/internal/operators/mergeInternals.js:17:70)
    at OperatorSubscriber._this._next (/builds/vN1UpTSL/18/bdc/neo2.0/node_modules/wait-on/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:28:21)
    at OperatorSubscriber.Subscriber.next (/builds/vN1UpTSL/18/bdc/neo2.0/node_modules/wait-on/node_modules/rxjs/dist/cjs/internal/Subscriber.js:72:18)
    at AsyncAction.work (/builds/vN1UpTSL/18/bdc/neo2.0/node_modules/wait-on/node_modules/rxjs/dist/cjs/internal/observable/timer.js:28:28)
    at AsyncAction._execute (/builds/vN1UpTSL/18/bdc/neo2.0/node_modules/wait-on/node_modules/rxjs/dist/cjs/internal/scheduler/AsyncAction.js:76:18)
    at AsyncAction.execute (/builds/vN1UpTSL/18/bdc/neo2.0/node_modules/wait-on/node_modules/rxjs/dist/cjs/internal/scheduler/AsyncAction.js:64:26)
    at AsyncScheduler.flush (/builds/vN1UpTSL/18/bdc/neo2.0/node_modules/wait-on/node_modules/rxjs/dist/cjs/internal/scheduler/AsyncScheduler.js:39:33)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
```

From the logs, Angular's ng serve is not yet done.  The site is not yet up.  Is there a way to delay the check of the target site to wait for the completion of ng serve?

**Comment by devkat** [comment]
Setting `WAIT_ON_TIMEOUT` worked for me: 

~~~
    "test:dev:headless": "WAIT_ON_TIMEOUT=1200000 start-test 'npm run e2e' :4000 'npm run cypress:headless'"
~~~

**Comment by dereklin** [comment]
Thanks. WAIT_ON_TIMEOUT worked for me.
