### ISSUE TITLE
start-server-and-test ends in ambiguous error after tests run

### ISSUE THREAD

**Issue by pbracken** [bahmutov/start-server-and-test#364]
I am attempting to use start-server-and-test module to run cypress tests in the command line. Whenever I run it, it properly starts up the angular server and then runs through all of my tests. When it finishes the tests it errors out with the nondescript error message below. Any idea what could be causing this? I can run each step individually without start-server-and-test and they all work fine with no issues.

Package.json relevant lines

```
"scripts": {
  "start": "ng serve --proxy-config proxy.conf.json",
  "cypress:run": "cypress run",
  "start-chrome": "start-server-and-test start http://localhost:4200 cypress:run"
}
```
Error message:

```
Error: Command failed with exit code 32: npm run cypress:run
    at makeError (C:\Users\User\source\repos\syntelic-angular-ui\SynUI\syntelic-ui\node_modules\execa\lib\error.js:60:11)
    at handlePromise (C:\Users\User\source\repos\syntelic-angular-ui\SynUI\syntelic-ui\node_modules\execa\index.js:118:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  shortMessage: 'Command failed with exit code 32: npm run cypress:run',
  command: 'npm run cypress:run',
  escapedCommand: '"npm run cypress:run"',
  exitCode: 32,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**Comment by pbracken** [comment]
Turns out this is thrown when a test fails in the cypress run
