### ISSUE TITLE
Error: kill ESRCH

### ISSUE THREAD

**Issue by nWidart** [bahmutov/start-server-and-test#46]
## Is this a bug report or a feature request?

Bug report

If this is a bug report, please provide as much info as possible

- version `1.4.1`
- platform: `teamcity`

*expected behavior*

The server to run in CI environment.

*actual behavior*

The command crashes with the following info:

```
[04:09:56][Step 3/6] { Error: kill ESRCH
[04:09:56][Step 3/6]     at exports._errnoException (util.js:1018:11)
[04:09:56][Step 3/6]     at process.kill (internal/process.js:190:13)
[04:09:56][Step 3/6]     at children.forEach.child (/home/teamcity/buildAgent/work/7182f89e35c6b1c9/node_modules/start-server-and-test/src/index.js:32:21)
[04:09:56][Step 3/6]     at Array.forEach (native)
[04:09:56][Step 3/6]     at Promise.fromNode.then.children (/home/teamcity/buildAgent/work/7182f89e35c6b1c9/node_modules/start-server-and-test/src/index.js:31:20)
[04:09:56][Step 3/6]     at tryCatcher (/home/teamcity/buildAgent/work/7182f89e35c6b1c9/node_modules/bluebird/js/release/util.js:16:23)
[04:09:56][Step 3/6]     at Promise._settlePromiseFromHandler (/home/teamcity/buildAgent/work/7182f89e35c6b1c9/node_modules/bluebird/js/release/promise.js:512:31)
[04:09:56][Step 3/6]     at Promise._settlePromise (/home/teamcity/buildAgent/work/7182f89e35c6b1c9/node_modules/bluebird/js/release/promise.js:569:18)
[04:09:56][Step 3/6]     at Promise._settlePromise0 (/home/teamcity/buildAgent/work/7182f89e35c6b1c9/node_modules/bluebird/js/release/promise.js:614:10)
[04:09:56][Step 3/6]     at Promise._settlePromises (/home/teamcity/buildAgent/work/7182f89e35c6b1c9/node_modules/bluebird/js/release/promise.js:693:18)
[04:09:56][Step 3/6]     at Promise._fulfill (/home/teamcity/buildAgent/work/7182f89e35c6b1c9/node_modules/bluebird/js/release/promise.js:638:18)
[04:09:56][Step 3/6]     at /home/teamcity/buildAgent/work/7182f89e35c6b1c9/node_modules/bluebird/js/release/nodeback.js:42:21
[04:09:56][Step 3/6]     at /home/teamcity/buildAgent/work/7182f89e35c6b1c9/node_modules/ps-tree/index.js:86:7
[04:09:56][Step 3/6]     at Stream.a.end (/home/teamcity/buildAgent/work/7182f89e35c6b1c9/node_modules/event-stream/index.js:87:5)
[04:09:56][Step 3/6]     at Stream.onend (internal/streams/legacy.js:44:10)
[04:09:56][Step 3/6]     at emitNone (events.js:91:20) code: 'ESRCH', errno: 'ESRCH', syscall: 'kill' }
[04:09:56][Step 3/6] error An unexpected error occurred: "Command failed.
[04:09:56][Step 3/6] Exit code: 1
[04:09:56][Step 3/6] Command: sh
[04:09:56][Step 3/6] Arguments: -c start-server-and-test start http://localhost:3000 cypress:run:ci
[04:09:56][Step 3/6] Directory: /home/teamcity/buildAgent/work/7182f89e35c6b1c9
[04:09:56][Step 3/6] Output:
[04:09:56][Step 3/6] ".
```

Here are the relevant commands I'm running:

```
"watch-css": "npm run build-css && node-sass-chokidar src/css/scss/ -o src/css/dist/ --watch",
"start": "npm-run-all -p watch-css start-js",
"cypress:run:ci": "./node_modules/.bin/cypress run",
"cypress:ci": "start-server-and-test start http://localhost:3000 cypress:run:ci"
```

`cypress:ci` being the one called in teamcity.

When I run this command locally, it works fine.

Thank you!

**Comment by bahmutov** [comment]
Hmm, probably because there are several things watching over the files and running.

**Comment by runarb** [comment]
@nWidart I'm having the exact same problem on Travis! Posted on SOF yesterday: https://stackoverflow.com/questions/50153861/travis-fails-when-cypress-tests-finish-successfully-run-with-webpack-dev-server

Ended up with a workaround, but still curious about what's causing this error.

**Comment by runarb** [comment]
@bahmutov My script is even simpler, but is also failing. From an outsider's perspective it simply looks like the Cypress process terminates itself and then `start-server-and-test` tries to kill the process with out checking whether it still exists... Just an assumption. 

Still doesn't explain why it works locally, but not on the CI server though.

**Comment by nWidart** [comment]
@runarb hm the tests aren't even running here, it kills before cypress can start.

**Comment by bahmutov** [comment]
If I could get my hands on a Travis reproducible example (I don't have access to a TeamCity build), I could look into this bug

**Comment by morficus** [comment]
I'm running in to the same issue but I'm using Docker (and `cypress/base:8` as the base image)

* version: `1.7.0`
* platform: `Debian running in a docker container`

Here are my scripts:

```
"e2e:ci": "start-server-and-test start:ci http-get://localhost:8080 e2e:headless",
"start:ci": "npm start > /dev/null",
"start": "concurrently --kill-others --raw \"npm:ui\" \"npm:api\" ",
"ui": "vue-cli-service serve",
"api": "nodemon dev-server.js",
"e2e:headless": "cypress run --reporter mocha-multi-reporters --reporter-options configFile=tests/e2e/reporters.json --config watchForFileChanges=false",
```

and here is the error output:

```
{ Error: kill ESRCH
    at Object._errnoException (util.js:992:11)
    at process.kill (internal/process.js:183:18)
    at children.forEach.child (/app/node_modules/start-server-and-test/src/index.js:38:21)
    at Array.forEach (<anonymous>)
    at Promise.fromNode.then.children (/app/node_modules/start-server-and-test/src/index.js:37:20)
    at tryCatcher (/app/node_modules/start-server-and-test/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/app/node_modules/start-server-and-test/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/app/node_modules/start-server-and-test/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/app/node_modules/start-server-and-test/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/app/node_modules/start-server-and-test/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/app/node_modules/start-server-and-test/node_modules/bluebird/js/release/promise.js:638:18)
    at /app/node_modules/start-server-and-test/node_modules/bluebird/js/release/nodeback.js:42:21
    at /app/node_modules/ps-tree/index.js:86:7
    at Stream.a.end (/app/node_modules/event-stream/index.js:87:5)
    at Stream.onend (internal/streams/legacy.js:44:10)
    at emitNone (events.js:111:20) code: 'ESRCH', errno: 'ESRCH', syscall: 'kill' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vision-ui@1.1.0-dev e2e:ci: `start-server-and-test start:ci http-get://localhost:8080 e2e:headless`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vision-ui@1.1.0-dev e2e:ci script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

**Comment by kyleoliveiro** [comment]
Also running into this issue. I'm using Cypress as part of my test pipeline as well. Sometimes there are no errors, sometimes this occurs before the Cypress tests run, and other times it occurs after all my tests have run (and passed).

**Comment by nouh** [comment]
also have the same issue when using cypress

**Comment by kentcdodds** [comment]
I'm having this issue as well: https://travis-ci.org/kentcdodds/jest-cypress-react-babel-webpack/builds/431335692

**Comment by wlsf82** [comment]
I am also getting a similar error when running tests on SemaphoreCI
```
Subprocess killed from getting SIGTERM
{ Error: kill ESRCH
    at process.kill (internal/process.js:172:20)
```
Locally it always works.

**Comment by wlsf82** [comment]
Hi @morficus, well, my local environment is a MacOS, and the environment on SemaphoreCI is Linux.
Also, even on SemaphoreCI sometimes it kills the processes correctly, but sometimes I get the error, while locally I never got the error.

**Comment by wlsf82** [comment]
Just to update you on our specific issue, seems that ours is Bazel's related (https://github.com/bazelbuild/rules_nodejs/pull/256)
